int32 average_length
---
float64 x
float64 y
float64 heading
float64 bearing
float64 mob_rad_0_l_error
float64 mob_rad_0_r_error
float64 mob_rad_1_l_error
float64 mob_rad_1_r_error
float64 max_angle_error
bool fail
