int32 average_length
---
float64 x
float64 y
float64 heading
float64 bearing
float64 mob_rad_0_l_dev
float64 mob_rad_0_r_dev
float64 mob_rad_1_l_dev
float64 mob_rad_1_r_dev
float64 max_angle_error
bool base_L_failure
bool base_R_failure
bool mob_L_failure
bool mob_R_failure
bool triangulation_failure
bool fail
