# A
int16 c1_amps
int16 c2_amps

# AI
int16 c1_analog_inputs
int16 c2_analog_inputs

# AIC
int16 c1_analog_inputs_conversion
int16 c2_analog_inputs_conversion

# BA
int16 c1_battery_amps
int16 c2_battery_amps

# BCR
int32 c1_brushless_count_relative
int32 c2_brushless_count_relative

# BS
int16 c1_bl_motor_speed_rpm
int16 c2_bl_motor_speed_rpm

# CB
int32 c1_absolute_brushless_counter
int32 c2_absolute_brushless_counter

# DI
bool c1_individual_digital_inputs
bool c2_individual_digital_inputs

# DR
uint8 c1_destination_reached
uint8 c2_destination_reached

# FF
uint8 fault_flags
# Where
# f1 = Overheat
# f2 = Overvoltage
# f3 = Undervoltage
# f4 = Short circuit
# f5 = Emergency stop
# f6 = Brushless sensor fault
# f7 = MOSFET failure
# f8 = Default configuration loaded at startup
