# A
int16[] motor_amps

# AI
int16[] analog_inputs

# AIC
int16[] analog_inputs_conversion

# BA
int16[] battery_amps

# BCR
int32[] brushless_count_relative

# BS
int16[] bl_motor_speed_rpm

# CB
int32[] absolute_brushless_counter

# DI
bool[] individual_digital_inputs

# DR
uint8[] destination_reached

# FF 
uint8 fault_flags
# Where
# f1 = Overheat
# f2 = Overvoltage
# f3 = Undervoltage
# f4 = Short circuit
# f5 = Emergency stop
# f6 = Brushless sensor fault
# f7 = MOSFET failure
# f8 = Default configuration loaded at startup
